### create
POST {{host}}/study-group
Content-Type: application/json

{
  "title" : "dsg2",
  "content": "test content02"
}


### getById
GET {{host}}/study-group/2


### getAll
GET {{host}}/study-group


### updateById
PUT {{host}}/study-group/2
Content-Type: application/json

{
  "title" : "dsg_new",
  "content": "test_new"
}

### deleteById
DELETE {{host}}/study-group/6


### getAllByUserId
GET http://localhost:8081/user/1/study-group

